import {
  Activity,
  AlertTriangle,
  ArrowDownCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowUpFromLine,
  BarChart,
  Bell,
  Bolt,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  Clock,
  Gamepad,
  Info,
  Lightbulb,
  Shield,
  ShoppingBag,
  SortAsc,
  Copy,
  CreditCard,
  Download,
  Droplet,
  File,
  FileSearch,
  FileText,
  Filter,
  FilterX,
  Fingerprint,
  Flame,
  HelpCircle,
  Heart,
  History,
  Home,
  Image,
  Inbox,
  Landmark,
  Laptop,
  LayoutDashboard,
  Layers,
  Link,
  Loader2,
  LogOut,
  LucideProps,
  Mail,
  Megaphone,
  Menu,
  MessageSquare,
  MoreHorizontal,
  Package,
  Phone,
  PieChart,
  Plus,
  QrCode,
  Repeat,
  RefreshCw,
  Search,
  Settings,
  Share,
  ShoppingCart,
  Smartphone,
  Star,
  Sun,
  Tablet,
  Ticket,
  Trash,
  Trophy,
  Truck,
  Tv,
  User,
  Users,
  Wallet,
  Wifi,
  Zap,
} from "lucide-react";

export type IconProps = LucideProps;

export const Icons = {
  activity: Activity,
  alertTriangle: AlertTriangle,
  arrowDownCircle: ArrowDownCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpCircle: ArrowUpCircle,
  barChart: BarChart,
  bell: Bell,
  chartBar: BarChart, // Alias for barChart to support the PPOBAdminPage
  arrowUpFromLine: ArrowUpFromLine,
  filter: Filter,
  gamepad: Gamepad,
  lightbulb: Lightbulb,
  shield: Shield,
  shopping: ShoppingBag,
  sort: SortAsc,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsDown: ChevronsDown,
  clock: Clock,
  copy: Copy,
  creditCard: CreditCard,
  download: Download,
  droplet: Droplet,
  file: File,
  fileSearch: FileSearch,
  filterX: FilterX,
  flame: Flame,
  heart: Heart,
  history: History,
  home: Home,
  inbox: Inbox,
  info: Info,
  layers: Layers,
  link: Link,
  logOut: LogOut,
  megaphone: Megaphone,
  menu: Menu,
  messageSquare: MessageSquare,
  mail: Mail,
  package: Package,
  phone: Phone,
  plus: Plus,
  qrCode: QrCode,
  repeat: Repeat,
  refreshCw: RefreshCw,
  undo: RefreshCw, // Using RefreshCw as Undo since Undo isn't in lucide-react
  search: Search,
  settings: Settings,
  share: Share,
  shoppingCart: ShoppingCart,
  smartphone: Smartphone,
  spinner: Loader2,
  ticket: Ticket,
  trash: Trash,
  truck: Truck,
  tv: Tv,
  users: Users,
  wallet: Wallet,
  wifi: Wifi,
  zap: Zap,
};
