
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Import CustomDatabase as Database from custom-types.ts
import type { CustomDatabase as Database } from './custom-types';

const SUPABASE_URL = "https://vpztrjwitxvldrdhndlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwenRyandpdHh2bGRyZGhuZGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTE3NzIsImV4cCI6MjA2MzM4Nzc3Mn0._NFTwCpQGgMThUeh1sew8y5ulRXSGmwHLmXRQx544PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with options for better error handling
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'jpc-digi-auth',
  },
});

// Add error handling for token refresh failures
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED' && !session) {
    // Handle case where token refresh failed
    console.log('Token refresh failed, redirecting to login');
    // Clear any potentially corrupted session data
    supabase.auth.signOut().catch(e => console.error('Error signing out:', e));
    
    // Only redirect if we're not already on the login page
    if (!window.location.pathname.includes('/login')) {
      setTimeout(() => {
        window.location.href = '/login';
      }, 500);
    }
  }
});
